using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class FactManager : MonoBehaviour
{
    public TextMeshProUGUI factText; // Assign the UI Text in the Inspector
    private Dictionary<string, List<string>> planetFacts = new Dictionary<string, List<string>>();
    public string celestialBody;
    void Start()
    {
        LoadFacts(); // Load facts into the dictionary
        ShowRandomFacts(celestialBody); // Default to Earth
    }

    void LoadFacts()
    {
        planetFacts["Mercury"] = GetMercuryFacts();
        planetFacts["Venus"] = GetVenusFacts();
        planetFacts["Earth"] = GetEarthFacts();
        planetFacts["Mars"] = GetMarsFacts();
        planetFacts["Jupiter"] = GetJupiterFacts();
        planetFacts["Saturn"] = GetSaturnFacts();
        planetFacts["Uranus"] = GetUranusFacts();
        planetFacts["Neptune"] = GetNeptuneFacts();
        planetFacts["Sun"] = GetSunFacts();
    }

    public void ShowRandomFacts(string celestialBody)
    {
        
        if (planetFacts.ContainsKey(celestialBody))
        {
            List<string> randomFacts = GetRandomFacts(planetFacts[celestialBody], 3);
            factText.text = string.Join("\n\n", randomFacts);
        }
        else
        {
            factText.text = "No facts available for " + celestialBody;
        }
    }

    private List<string> GetRandomFacts(List<string> facts, int count)
    {
        List<string> selectedFacts = new List<string>();
        List<string> tempList = new List<string>(facts);

        for (int i = 0; i < count && tempList.Count > 0; i++)
        {
            int randomIndex = Random.Range(0, tempList.Count);
            selectedFacts.Add(tempList[randomIndex]);
            tempList.RemoveAt(randomIndex);
        }

        return selectedFacts;
    }

    private List<string> GetMercuryFacts()
    {
        return new List<string>
    {
        "Mercury is the smallest planet in the solar system.",
        "A day on Mercury (one full rotation) lasts about 59 Earth days.",
        "A year on Mercury (one full orbit) lasts only 88 Earth days.",
        "Mercury has no atmosphere to retain heat, making it the planet with the largest temperature variation.",
        "The temperature on Mercury can drop to -173°C at night and rise to 427°C during the day.",
        "Mercury is the closest planet to the Sun, at an average distance of 57.9 million km.",
        "Mercury has a metallic core that makes up about 85% of its radius.",
        "Mercury has no moons or rings.",
        "The surface of Mercury is covered with craters, similar to Earth's Moon.",
        "The largest crater on Mercury is the Caloris Basin, which is about 1,550 km in diameter.",
        "Mercury has a weak magnetic field, about 1% as strong as Earth's.",
        "The MESSENGER spacecraft mapped Mercury in detail.",
        "Mercury has cliffs called scarps, which are up to 3 km high and 600 km long.",
        "Mercury's gravity is about 38% of Earth's.",
        "If you weigh 100 kg on Earth, you would weigh only 38 kg on Mercury.",
        "Mercury is made mostly of rock and metal.",
        "Despite being closest to the Sun, Mercury is not the hottest planet—Venus is.",
        "The first spacecraft to visit Mercury was Mariner 10 in 1974.",
        "Mercury is named after the Roman messenger god due to its fast movement in the sky.",
        "Mercury's orbit is highly elliptical, meaning its distance from the Sun varies greatly.",
        "Mercury is difficult to observe from Earth due to its proximity to the Sun.",
        "There is evidence that Mercury has water ice in permanently shadowed craters at its poles.",
        "Mercury's core is partly liquid, unlike Earth's solid inner core.",
        "Mercury spins very slowly compared to its orbit speed.",
        "A spacecraft launch to Mercury requires a lot of energy to slow down upon arrival due to the Sun’s gravity.",
        "Mercury has long, bright rays extending from craters, similar to the Moon.",
        "The Sun appears more than three times larger in Mercury's sky than it does from Earth.",
        "Mercury has no weather, rain, or wind.",
        "Temperatures at Mercury's poles are among the coldest in the solar system despite its proximity to the Sun.",
        "The planet's thin exosphere is made of oxygen, sodium, hydrogen, helium, and potassium.",
        "Mercury’s surface has wrinkles due to the planet cooling and contracting over time.",
        "The planet’s rotation and orbit create extreme day-night cycles.",
        "Sunlight on Mercury is 7 times stronger than on Earth.",
        "Mercury is 4.5 billion years old, just like the rest of the solar system.",
        "Mercury has been visited by two spacecraft: Mariner 10 and MESSENGER.",
        "Mercury is visible from Earth without a telescope but is hard to spot.",
        "Mercury is the second-densest planet after Earth.",
        "The planet has no tectonic plates.",
        "The planet is shrinking as its interior cools, creating cliffs on its surface.",
        "Mercury’s thin atmosphere does not provide protection from space weather.",
        "The planet's dark color comes from carbon-rich material on its surface.",
        "Mercury's weak gravity makes it unable to hold a thick atmosphere.",
        "Mercury’s orbit is influenced by the Sun’s gravity in a unique way.",
        "Unlike Earth, Mercury does not experience seasons.",
        "Mercury's core makes up a much larger proportion of its mass compared to Earth.",
        "Despite its small size, Mercury has a significant gravitational effect on its surroundings.",
        "The first detailed images of Mercury came from Mariner 10 in 1974.",
        "Mercury is one of the five planets known since ancient times.",
        "There is no evidence of life on Mercury.",
        "Mercury has high radar reflectivity at its poles due to ice deposits.",
        "Mercury moves faster than any other planet in the solar system.",
        "Mercury’s orbit is the most eccentric of all the planets.",
        "The Sun would appear to move backward in Mercury’s sky at certain points due to its orbital motion.",
        "Mercury does not have a true atmosphere, only a very thin exosphere.",
        "Mercury has been impacted by many asteroids and comets over billions of years.",
        "The Caloris Basin was formed by a massive impact, likely from an asteroid.",
        "The first probe to orbit Mercury was MESSENGER in 2011.",
        "Mercury’s night sky is always black due to its lack of atmosphere.",
        "Scientists believe Mercury’s core may be composed of mostly iron.",
        "Mercury’s days are longer than its years.",
        "Mercury’s axis has the smallest tilt of any planet in the solar system.",
        "Mercury has hollows—unique depressions on its surface likely caused by material loss.",
        "The planet's surface is covered in a fine dust called regolith.",
        "Mercury has experienced volcanic activity in the past.",
        "Mercury does not have rings or any natural satellites.",
        "Mercury is sometimes visible to the naked eye from Earth, but only near sunrise or sunset.",
        "The planet's small size and high density suggest it once had a larger outer layer that was stripped away.",
        "Mercury's orbit is affected by Einstein’s theory of general relativity.",
        "The Sun's gravitational influence makes Mercury's orbit precess over time.",
        "Mercury's surface has high amounts of sulfur compared to other rocky planets.",
        "Mercury has some of the oldest surface features in the solar system.",
        "MESSENGER found evidence of past volcanic eruptions on Mercury.",
        "Mercury does not have an ozone layer to protect it from solar radiation.",
        "Mercury’s exosphere is replenished by solar wind and micrometeorite impacts.",
        "The surface of Mercury contains small amounts of graphite.",
        "Mercury has fewer large mountains than Earth and Mars.",
        "Mercury is the most cratered planet in the solar system.",
        "The planet’s rotation is gradually slowing down.",
        "A spacecraft takes years to reach Mercury due to the Sun’s strong gravity.",
        "Mercury’s surface has features known as ‘spider’ craters—radiating cracks caused by impacts.",
        "Mercury has higher surface gravity than the Moon despite being similar in size.",
        "Its core is unusually large compared to its overall size.",
        "Mercury’s surface is darker than the Moon’s due to carbon-rich material.",
        "Mercury may have once had a thicker atmosphere that was lost over time.",
        "It has the lowest axial tilt of any planet, at just 0.034 degrees.",
        "Some craters near Mercury’s poles are permanently shadowed and contain ice.",
        "Mercury's weak gravity means it cannot hold onto gases like Earth does.",
        "The Sun’s radiation bombards Mercury’s surface directly.",
        "Mercury’s orbit is tilted 7 degrees relative to Earth's orbit.",
        "The Caloris impact caused seismic waves to travel around the planet.",
        "Mercury’s perihelion (closest point to the Sun) is gradually shifting.",
        "It has ‘wrinkle ridges’ formed as its interior cooled and contracted.",
        "Mercury's rotation and orbit create strange sunrise and sunset effects.",
        "The surface temperature difference between day and night is the largest of any planet.",
        "Mercury's surface is heavily pitted with impact craters from ancient collisions.",
        "MESSENGER revealed Mercury’s core is larger than previously thought.",
        "Unlike Venus or Mars, Mercury lacks large valleys or canyons.",
        "Mercury has been studied since ancient times by many civilizations.",
        "The next mission to Mercury is BepiColombo, launched in 2018 and set to arrive in 2025."
    };
    }


    private List<string> GetVenusFacts()
    {
        return new List<string>
    {
        "Venus is the second planet from the Sun.",
        "Venus is the hottest planet in the solar system.",
        "A day on Venus (one full rotation) lasts about 243 Earth days.",
        "A year on Venus (one full orbit) lasts only 225 Earth days.",
        "Venus rotates in the opposite direction of most planets, including Earth.",
        "Venus has a thick atmosphere primarily composed of carbon dioxide.",
        "The surface temperature on Venus can reach 467°C (872°F).",
        "Venus has clouds of sulfuric acid that make it highly reflective.",
        "Venus is often called Earth's 'sister planet' due to its similar size and composition.",
        "Venus is the brightest natural object in Earth's night sky after the Moon.",
        "Venus has no moons or rings.",
        "The pressure on Venus' surface is about 92 times that of Earth's.",
        "Venus' atmosphere traps heat in an extreme greenhouse effect.",
        "Venus has no water on its surface due to its extreme heat.",
        "Venus' surface is covered with volcanoes, mountains, and vast plains.",
        "The tallest mountain on Venus is Maxwell Montes, which is about 11 km high.",
        "Venus' clouds make it impossible to see its surface with normal telescopes.",
        "The first spacecraft to visit Venus was Mariner 2 in 1962.",
        "Venus is named after the Roman goddess of love and beauty.",
        "Venus' thick atmosphere causes intense surface winds.",
        "Venus has more volcanoes than any other planet in the solar system.",
        "The Soviet Union's Venera program sent multiple landers to Venus.",
        "Venus' rotation is so slow that a day is longer than a year.",
        "The planet's surface has been mapped by radar due to its thick clouds.",
        "Venus experiences lightning, even without rain.",
        "Venus is the closest planet to Earth in terms of distance.",
        "Venus has a weak magnetic field compared to Earth.",
        "Venus' surface temperature is hot enough to melt lead.",
        "Venus does not have plate tectonics like Earth.",
        "Venus' clouds reflect about 75% of sunlight, making it extremely bright.",
        "The Venera landers survived only a few minutes to hours on Venus' surface due to extreme conditions.",
        "Venus' atmosphere is mostly carbon dioxide with traces of nitrogen and sulfur dioxide.",
        "Venus' extreme heat is due to its runaway greenhouse effect.",
        "Venus' sky appears orange due to its thick atmosphere.",
        "Venus' winds in the upper atmosphere reach speeds of 360 km/h.",
        "Venus is slightly smaller than Earth, with about 95% of its diameter.",
        "Venus' rotation is retrograde, meaning it spins in the opposite direction of Earth.",
        "Venus' surface has vast lava plains formed by volcanic activity.",
        "Venus' thick atmosphere prevents most meteoroids from reaching its surface.",
        "Venus is sometimes called the 'Morning Star' or 'Evening Star' due to its brightness.",
        "Venus has been studied since ancient times.",
        "Venus' clouds contain sulfuric acid, making the atmosphere highly corrosive.",
        "Radar mapping has revealed that Venus has large impact craters.",
        "Venus' surface is relatively young, estimated to be around 300-600 million years old.",
        "Venus has a very slow rotation, taking 243 Earth days to complete one spin.",
        "The atmosphere of Venus rotates much faster than the planet itself, a phenomenon called super-rotation.",
        "Venus' orbit is the most circular of any planet in the solar system.",
        "Venus is the third brightest object in Earth's sky after the Sun and Moon.",
        "No spacecraft has ever lasted more than a few hours on Venus' surface.",
        "Venus' clouds make it impossible to see the surface with visible light.",
        "Venus is believed to have had liquid water in the past before its greenhouse effect took over.",
        "Venus' gravity is about 90% of Earth's gravity.",
        "Venus does not have a significant tilt, meaning it does not have seasons like Earth.",
        "The Pioneer Venus mission studied the planet's atmosphere in the late 1970s.",
        "Venus' thick clouds make it difficult for heat to escape, contributing to its high temperatures.",
        "Venus' atmosphere is dense enough to crush a spacecraft that lands on its surface.",
        "The pressure at Venus' surface is equivalent to being 900 meters underwater on Earth.",
        "Venus has been explored by orbiters, landers, and flyby missions.",
        "Venus has no known magnetic field to protect it from solar radiation.",
        "Some scientists believe Venus may have been habitable in the distant past.",
        "The first successful Venus lander was Venera 7 in 1970.",
        "Venus Express, launched by ESA, studied the planet from 2006 to 2014.",
        "Venus' atmosphere creates a 'double sunrise' effect due to light refraction.",
        "Venus has been considered for human colonization using floating cities in its upper atmosphere.",
        "Venus' rotation is so slow that a Venusian day lasts longer than a Venusian year.",
        "The Akatsuki probe, launched by Japan, is currently studying Venus' atmosphere.",
        "Venus' temperature remains nearly constant across day and night due to its thick atmosphere.",
        "Venus' clouds contain trace amounts of phosphine, a possible sign of microbial life.",
        "Venus' surface has features called coronae, which are formed by volcanic activity.",
        "Venus' atmosphere is about 96% carbon dioxide.",
        "Venus' surface is extremely dry, with no liquid water present.",
        "Venus' slow rotation causes its days to last longer than its years.",
        "Venus is visible to the naked eye and has been known since ancient times.",
        "Venus' clouds are highly reflective, giving the planet a bright white appearance.",
        "Venus has regions of lava flows that suggest recent volcanic activity.",
        "Venus has a runaway greenhouse effect due to its thick atmosphere.",
        "Venus' atmosphere rotates much faster than the planet itself, creating strong winds.",
        "Venus' clouds move at hurricane-force speeds in the upper atmosphere.",
        "Venus was once thought to have oceans before scientists discovered its extreme conditions.",
        "Venus has the most volcanoes of any planet in the solar system.",
        "Venus' surface shows evidence of past volcanic eruptions.",
        "Venus' atmosphere is thick enough to slow down and burn up meteoroids before they reach the ground.",
        "Venus has no significant axial tilt, meaning it does not experience seasons.",
        "Venus' atmosphere scatters sunlight, making the planet appear bright from Earth.",
        "Venus' clouds make its surface completely invisible from space.",
        "Venus' temperature is the same at its poles and equator due to its thick atmosphere.",
        "Venus' air is so thick that standing on the surface would feel like being deep underwater.",
        "Venus' sky is a yellowish-orange color due to its thick atmosphere.",
        "Venus' pressure would instantly crush an unprotected human on its surface.",
        "Venus' high surface temperatures make it impossible for liquid water to exist.",
        "Venus is the only planet in the solar system that rotates clockwise.",
        "Venus' thick clouds reflect most sunlight, keeping it bright in Earth's sky.",
        "Venus' surface is relatively young compared to other planets.",
        "Venus' upper atmosphere experiences extreme winds much faster than the planet's rotation.",
        "Venus' slow rotation and dense atmosphere create unique weather patterns.",
        "Venus is a prime target for future robotic exploration missions."
    };
    }


    private List<string> GetEarthFacts()
    {
        return new List<string>
        {
            "Earth is the only planet known to support life.",
            "Earth is the only planet known to support life.",
"70% of Earth's surface is covered by water.",
"Earth’s atmosphere is 78% nitrogen and 21% oxygen.",
"The Earth's core is as hot as the Sun's surface.",
"A day on Earth is gradually getting longer.",
"Earth's gravity is 9.8 m/s².",
"Earth is 4.5 billion years old.",
"The Moon is slowly drifting away from Earth.",
"The deepest part of the ocean is the Mariana Trench.",
"The Amazon rainforest produces 20% of Earth's oxygen.",
"The Earth's rotation is slowing down by 1.7 milliseconds per century.",
"Earth is the densest planet in the solar system.",
"The Pacific Ocean is the largest ocean on Earth.",
"Mount Everest is the tallest mountain above sea level.",
"Earth has a powerful magnetic field.",
"A year on Earth is 365.24 days long.",
"The ozone layer protects Earth from harmful UV rays.",
"Antarctica is the coldest place on Earth.",
"The Sahara Desert is the largest hot desert on Earth.",
"Earth’s atmosphere extends up to 10,000 km into space.",
"More than 80% of the ocean is unexplored.",
"Lightning strikes Earth about 100 times per second.",
"Earth has had 5 major extinction events.",
"Earthquakes occur due to tectonic plate movements.",
"The longest river on Earth is the Nile.",
"The Dead Sea is the lowest point on land.",
"Greenland is the world’s largest island.",
"The Great Barrier Reef is the largest coral reef system.",
"Earth’s core is made of iron and nickel.",
"The Moon's gravity causes ocean tides.",
"The Earth wobbles slightly on its axis.",
"The Andromeda Galaxy is moving towards Earth.",
"The Earth's inner core is solid, while the outer core is liquid.",
"Earth experiences about 500,000 detectable earthquakes per year.",
"One lightning bolt is five times hotter than the surface of the Sun.",
"The Amazon River is the second longest river on Earth.",
"The Arctic is warming twice as fast as the rest of the planet.",
"Lake Baikal in Russia is the world's deepest freshwater lake.",
"Earth has about 1.4 billion cubic kilometers of water.",
"The Earth's atmosphere makes up less than 1% of its mass.",
"The Earth orbits the Sun at an average speed of 107,000 km/h.",
"The Sunlight takes about 8 minutes to reach Earth.",
"Earth's equator is about 40,075 km in circumference.",
"The hottest temperature recorded on Earth was 56.7°C (134°F) in Death Valley, California.",
"The coldest temperature recorded was -128.6°F (-89.2°C) in Antarctica.",
"Earth’s atmosphere has changed over billions of years.",
"The majority of Earth's freshwater is stored in glaciers.",
"The Amazon is the world’s largest rainforest.",
"The Earth's surface is constantly changing due to erosion and plate tectonics.",
"Earth is the only known planet with liquid water on its surface.",
"The Earth's crust is divided into tectonic plates.",
"The first life on Earth appeared around 3.5 billion years ago.",
"Earth's magnetic field is created by its rotating core.",
"A day is not exactly 24 hours—it's about 23 hours, 56 minutes.",
"The speed of sound in Earth's atmosphere is about 343 m/s.",
"Earth has about 8.7 million species of life.",
"Earth is slightly flattened at the poles due to rotation.",
"The Earth's inner core is growing by about 1 mm per year.",
"The Great Lakes contain about 21% of the world's freshwater.",
"Earth's atmosphere shields us from meteors, burning them up before they reach the surface.",
"The oldest rocks on Earth are over 4 billion years old.",
"The longest-lived human was 122 years old.",
"The Earth has a natural satellite—our Moon.",
"Earth's average surface temperature is 15°C (59°F).",
"The Moon takes 27.3 days to orbit Earth.",
"Venus is often called Earth’s 'sister planet' due to similar size.",
"The deepest earthquake ever recorded was 700 km below Earth's surface.",
"The Himalayas are still growing due to plate movement.",
"There are more trees on Earth than stars in the Milky Way.",
"The Sahara Desert was once a lush green area.",
"Earth has more than 3 trillion trees.",
"Half of Earth's oxygen comes from the ocean.",
"Earth's rotation speed is slowing down due to tidal forces.",
"The Moon has no atmosphere to protect it from meteors.",
"The Mariana Trench is deeper than Mount Everest is tall.",
"Earth's magnetosphere protects it from solar wind.",
"The tallest tree on Earth is over 115 meters tall.",
"More than 200,000 earthquakes occur on Earth each year."
        };
    }

    private List<string> GetMarsFacts()
    {
        return new List<string>
    {
        "Mars is the fourth planet from the Sun.",
        "Mars is often called the 'Red Planet' due to its reddish appearance.",
        "Mars has the tallest volcano in the solar system, Olympus Mons.",
        "Olympus Mons is about three times taller than Mount Everest.",
        "Mars has the deepest and longest canyon in the solar system, Valles Marineris.",
        "Mars has two small moons, Phobos and Deimos.",
        "Phobos is gradually spiraling toward Mars and may eventually crash into the planet.",
        "Mars has the largest dust storms in the solar system.",
        "Mars' thin atmosphere is mostly carbon dioxide.",
        "A day on Mars (sol) is about 24 hours and 39 minutes long.",
        "A year on Mars lasts 687 Earth days.",
        "Mars' gravity is about 38% of Earth's gravity.",
        "Mars has evidence of ancient river valleys and lake beds.",
        "Mars' average surface temperature is about -63°C (-81°F).",
        "Water-ice exists beneath the surface of Mars.",
        "Mars experiences seasons similar to Earth due to its axial tilt.",
        "Mars' atmosphere is too thin to support liquid water on the surface for long.",
        "Mars' polar ice caps are made of water ice and dry ice (frozen carbon dioxide).",
        "The first successful Mars flyby was by NASA's Mariner 4 in 1965.",
        "NASA's Viking landers were the first to successfully land on Mars in 1976.",
        "Mars has been explored by multiple rovers, including Spirit, Opportunity, Curiosity, and Perseverance.",
        "Perseverance is currently exploring Mars and searching for signs of past life.",
        "Mars has the largest canyon system in the solar system, Valles Marineris, stretching over 4,000 km.",
        "Mars' sky appears reddish-orange due to fine dust particles in the atmosphere.",
        "Mars has weaker sunlight than Earth due to its greater distance from the Sun.",
        "Mars has no global magnetic field like Earth.",
        "Mars' thin atmosphere cannot block harmful cosmic radiation effectively.",
        "Mars' largest impact basin is Hellas Planitia.",
        "Mars' core is believed to be partially liquid, but not fully molten like Earth's.",
        "Mars has been the target of numerous failed and successful space missions.",
        "Mars has been a major focus of space agencies for potential human colonization.",
        "Mars' surface is covered in iron oxide, or rust, giving it a red color.",
        "Mars has been observed by humans since ancient times.",
        "Mars has a thin, dry atmosphere with almost no oxygen.",
        "Mars' surface pressure is less than 1% of Earth's surface pressure.",
        "Mars' temperatures can vary widely, from -140°C (-220°F) at the poles to 30°C (86°F) near the equator.",
        "Mars' atmosphere is so thin that liquid water would instantly evaporate or freeze.",
        "Mars' largest dust storms can last for months and cover the entire planet.",
        "Mars has impact craters that are billions of years old.",
        "Mars' exploration started with robotic missions before future human missions.",
        "Mars' crust is thicker than Earth's, and it lacks active plate tectonics.",
        "Mars' south pole has a large amount of frozen water ice beneath the surface.",
        "Mars has methane in its atmosphere, which could be a sign of microbial life or geological activity.",
        "Mars is half the size of Earth in diameter but has the same amount of dry land as Earth.",
        "Mars' surface is constantly bombarded by cosmic rays due to its weak atmosphere.",
        "Mars' sky can appear blue at sunset due to the way dust scatters sunlight.",
        "Mars' northern and southern hemispheres have different landscapes, with smooth lowlands in the north and rough highlands in the south.",
        "Mars is about 225 million km (140 million miles) away from Earth on average.",
        "Mars' thin atmosphere means sound travels differently than on Earth.",
        "Mars' surface has been shaped by volcanic activity, impacts, and wind erosion.",
        "Mars' craters show evidence of past water flow, indicating it once had rivers and lakes.",
        "Mars has no permanent liquid water on its surface today, only frozen water and seasonal briny flows.",
        "Mars is a key target for future human space exploration.",
        "Mars' largest volcano, Olympus Mons, is about 600 km (373 miles) in diameter.",
        "Mars' rotation axis tilts, similar to Earth's, causing its seasons.",
        "Mars' atmosphere allows for some very weak auroras caused by solar wind interactions.",
        "Mars' polar ice caps grow and shrink with the changing seasons.",
        "Mars' surface has large areas covered in sand dunes.",
        "Mars' soil contains perchlorates, chemicals that make it difficult for life as we know it to survive.",
        "Mars has seasonal carbon dioxide snowfalls near the poles.",
        "Mars' surface has been mapped extensively by orbiters.",
        "Mars' thin atmosphere results in a much lower atmospheric pressure compared to Earth.",
        "Mars' climate is cold and dry, but ancient Mars may have been warm and wet.",
        "Mars' orbit is more elliptical than Earth's, causing more extreme seasonal variations.",
        "Mars' average distance from the Sun is about 1.5 times that of Earth.",
        "Mars has been featured in many works of science fiction.",
        "Mars' exploration is crucial for understanding the potential for life beyond Earth.",
        "Mars' first soil analysis showed it contains essential nutrients for plants.",
        "Mars' sunsets appear blue due to dust scattering sunlight differently than on Earth.",
        "Mars has recurring slope lineae (RSL), dark streaks that may be caused by briny water.",
        "Mars' thin atmosphere means that liquid water would quickly evaporate or freeze.",
        "Mars has ancient river valleys that suggest liquid water once flowed on its surface.",
        "Mars has vast plains formed by lava flows.",
        "Mars' gravity is too weak to retain a thick atmosphere like Earth's.",
        "Mars' thin atmosphere allows more meteorites to reach its surface compared to Earth.",
        "Mars' orbit is inclined relative to the Sun, leading to extreme seasonal changes.",
        "Mars' low gravity affects how future astronauts will move and live on the planet.",
        "Mars has ancient lake beds that show signs of long-term water presence.",
        "Mars' rock formations provide clues about its geological history.",
        "Mars' lack of a thick atmosphere means it does not have significant weathering like Earth.",
        "Mars' distance from Earth varies from about 54 million km (34 million miles) to over 400 million km (250 million miles).",
        "Mars has been proposed as a backup planet for human survival in case of Earth disasters.",
        "Mars' magnetic field is weak and fragmented, unlike Earth's strong global magnetic field.",
        "Mars' atmosphere contains only about 0.13% oxygen, making it unsuitable for breathing.",
        "Mars has seasonal changes due to its axial tilt, just like Earth.",
        "Mars has been visited by landers, rovers, and orbiters from various space agencies.",
        "Mars' exploration will help scientists understand the potential for life on other planets.",
        "Mars' dust storms can create massive changes in the planet's climate for months.",
        "Mars' thin atmosphere means that it cannot retain much heat at night.",
        "Mars' first successful rover, Sojourner, landed in 1997 as part of the Mars Pathfinder mission.",
        "Mars is the most studied planet in the solar system after Earth.",
        "Mars' exploration continues with new missions planned for the future.",
        "Mars could one day be home to the first human colony beyond Earth."
    };
    }

    private List<string> GetJupiterFacts()
    {
        return new List<string>
    {
        "Jupiter is the largest planet in the solar system.",
        "Jupiter is the fifth planet from the Sun.",
        "Jupiter is a gas giant primarily composed of hydrogen and helium.",
        "Jupiter's Great Red Spot is a massive storm that has been raging for over 300 years.",
        "Jupiter has the strongest magnetic field of any planet in the solar system.",
        "Jupiter has at least 95 known moons, including Ganymede, the largest moon in the solar system.",
        "Jupiter's moon Europa may have an ocean beneath its icy surface, making it a candidate for extraterrestrial life.",
        "Jupiter rotates faster than any other planet, completing a rotation in about 10 hours.",
        "Jupiter’s gravity is 2.5 times stronger than Earth's gravity.",
        "Jupiter emits more heat than it receives from the Sun due to its internal processes.",
        "Jupiter has the shortest day of any planet in the solar system.",
        "Jupiter's atmosphere has colorful bands due to strong jet streams moving in opposite directions.",
        "Jupiter has faint, dark rings made of dust particles.",
        "Ganymede, one of Jupiter’s moons, is larger than the planet Mercury.",
        "Jupiter's four largest moons—Io, Europa, Ganymede, and Callisto—are called the Galilean moons.",
        "Jupiter’s core may be made of rock, metal, and hydrogen compounds.",
        "Jupiter's Great Red Spot is shrinking but still larger than Earth.",
        "Jupiter’s clouds are made of ammonia crystals and other elements.",
        "Jupiter has powerful auroras at its poles, caused by its strong magnetic field.",
        "Jupiter has been visited by several spacecraft, including Pioneer, Voyager, Galileo, and Juno.",
        "Jupiter has powerful winds that reach speeds of over 600 km/h (370 mph).",
        "Jupiter's atmosphere contains traces of methane, water vapor, and ammonia.",
        "Jupiter has been known since ancient times and is visible to the naked eye.",
        "Jupiter has no solid surface; it transitions gradually from gas to liquid.",
        "Jupiter’s fast rotation causes it to bulge at the equator.",
        "Jupiter's gravitational influence helps protect Earth from asteroids by deflecting them.",
        "Jupiter’s moon Io has the most volcanic activity of any body in the solar system.",
        "Jupiter’s magnetosphere is the largest structure in the solar system.",
        "Jupiter's orbit around the Sun takes about 12 Earth years.",
        "Jupiter's diameter is about 11 times that of Earth.",
        "Jupiter's volume is large enough to fit over 1,300 Earths inside it.",
        "Jupiter’s core may be surrounded by a layer of metallic hydrogen.",
        "Jupiter’s upper atmosphere contains fast-moving storms and lightning.",
        "Jupiter has been studied for centuries, but many of its mysteries remain unsolved.",
        "Jupiter has a thin ring system that was discovered by the Voyager spacecraft in 1979.",
        "Jupiter’s gravitational field influences the orbits of many asteroids in the solar system.",
        "Jupiter’s radiation belts are extremely strong, making it difficult for spacecraft to approach.",
        "Jupiter’s Great Red Spot was first observed in the 1600s.",
        "Jupiter’s atmosphere extends deep into the planet with increasing pressure.",
        "Jupiter is mostly made of gas and lacks a well-defined solid surface.",
        "Jupiter has massive lightning storms, some even larger than Earth's entire surface.",
        "Jupiter’s clouds can be over 50 km thick.",
        "Jupiter’s radiation is strong enough to be a major hazard for spacecraft.",
        "Jupiter’s moon Europa has a surface covered in ice and is believed to have an ocean beneath it.",
        "Jupiter’s moon Callisto is heavily cratered and one of the oldest surfaces in the solar system.",
        "Jupiter’s strong gravity makes it a key influence on many comets and asteroids.",
        "Jupiter was first observed through a telescope by Galileo Galilei in 1610.",
        "Jupiter’s storm systems can last for centuries.",
        "Jupiter’s fast rotation causes extreme weather patterns.",
        "Jupiter has white and brown ovals in its atmosphere, which are massive storm systems.",
        "Jupiter’s moon Ganymede has its own magnetic field, the only moon known to have one.",
        "Jupiter’s core temperature is estimated to be about 24,000°C (43,000°F).",
        "Jupiter’s upper clouds move in different directions due to jet streams.",
        "Jupiter’s gravitational influence helps shape the asteroid belt.",
        "Jupiter’s atmosphere has layers of different temperatures and compositions.",
        "Jupiter’s moons are some of the most studied objects in the solar system.",
        "Jupiter's magnetosphere extends far beyond the planet, reaching past Saturn's orbit.",
        "Jupiter’s size and mass make it the dominant planet in our solar system.",
        "Jupiter’s atmosphere has been studied to understand planetary weather patterns.",
        "Jupiter's fast rotation causes an equatorial bulge.",
        "Jupiter’s gravitational force is so strong that it slightly affects the Sun’s motion.",
        "Jupiter’s storms are powered by internal heat and its fast rotation.",
        "Jupiter’s rings are mainly composed of dust from its moons.",
        "Jupiter’s temperature varies greatly between its upper atmosphere and core.",
        "Jupiter’s gravity has been used by spacecraft for gravitational assists to other planets.",
        "Jupiter’s auroras are more powerful than Earth’s and are visible in ultraviolet light.",
        "Jupiter’s density is about one-fourth that of Earth’s, as it is mostly gas.",
        "Jupiter’s storms form and dissipate over different time periods.",
        "Jupiter’s powerful gravity influences the orbits of other planets slightly.",
        "Jupiter’s moons have diverse geological features, from volcanoes to ice-covered surfaces.",
        "Jupiter’s Great Red Spot has changed shape and color over time.",
        "Jupiter’s deep atmosphere contains exotic states of hydrogen, such as metallic hydrogen.",
        "Jupiter has been a major focus of scientific study due to its complexity.",
        "Jupiter’s moon Europa is a key target in the search for extraterrestrial life.",
        "Jupiter’s core may be dissolving into its atmosphere over time.",
        "Jupiter’s gravitational field is used in simulations to study planetary system formation.",
        "Jupiter’s radiation is so intense that spacecraft need heavy shielding to survive.",
        "Jupiter’s magnetic field traps charged particles, creating intense radiation belts.",
        "Jupiter’s interior remains largely mysterious due to its extreme conditions.",
        "Jupiter’s storm bands shift and change over time.",
        "Jupiter’s role in the solar system has been described as a 'cosmic vacuum cleaner' due to its gravitational pull on asteroids and comets.",
        "Jupiter’s immense size makes it easy to spot in the night sky.",
        "Jupiter’s weather is driven by both solar heating and internal heat.",
        "Jupiter’s storms can be as large as entire continents on Earth.",
        "Jupiter’s magnetosphere interacts with the solar wind, creating radio emissions.",
        "Jupiter’s mass is about 318 times that of Earth.",
        "Jupiter’s influence extends throughout the solar system due to its gravity.",
        "Jupiter’s rapid rotation flattens it slightly at the poles.",
        "Jupiter’s interior pressure is so high that hydrogen behaves like a metal.",
        "Jupiter’s Great Red Spot may eventually disappear, as it has been shrinking.",
        "Jupiter’s moon Io has over 400 active volcanoes, the most in the solar system.",
        "Jupiter’s exploration is ongoing, with future missions planned to study its moons and atmosphere.",
        "Jupiter remains one of the most fascinating and dynamic planets in our solar system."
    };
    }


    private List<string> GetSaturnFacts()
    {
        return new List<string>
    {
        "Saturn is the second-largest planet in the solar system.",
        "Saturn is the sixth planet from the Sun.",
        "Saturn is a gas giant primarily composed of hydrogen and helium.",
        "Saturn has the most extensive ring system of any planet in the solar system.",
        "Saturn’s rings are made mostly of ice, dust, and rock.",
        "Saturn has at least 146 confirmed moons, with Titan being the largest.",
        "Titan, Saturn’s largest moon, has a thick atmosphere and liquid methane lakes.",
        "Saturn’s density is so low that it would float in water if a large enough body of water existed.",
        "Saturn's rings extend up to 282,000 km (175,000 miles) from the planet.",
        "Saturn’s rings are divided into several sections, including the A, B, and C rings.",
        "Saturn’s largest moon, Titan, is bigger than the planet Mercury.",
        "Saturn's atmosphere is mostly made of hydrogen, with traces of helium and methane.",
        "Saturn's winds can reach speeds of up to 1,800 km/h (1,100 mph).",
        "Saturn has a hexagonal-shaped storm at its north pole.",
        "Saturn has been visited by several spacecraft, including Pioneer, Voyager, and Cassini.",
        "Saturn’s rings were first observed by Galileo Galilei in 1610, but he couldn’t identify them as rings.",
        "Christiaan Huygens was the first to correctly describe Saturn’s rings in 1655.",
        "Saturn’s rings are believed to be remnants of comets, asteroids, or shattered moons.",
        "Saturn takes about 29.5 Earth years to complete one orbit around the Sun.",
        "A day on Saturn lasts about 10 hours and 33 minutes.",
        "Saturn's magnetic field is weaker than Jupiter’s but still strong enough to trap radiation.",
        "Saturn’s rings are constantly changing due to gravitational interactions with its moons.",
        "Some of Saturn’s moons, like Enceladus, have subsurface oceans that may harbor life.",
        "Saturn has a rapid rotation that causes it to be visibly flattened at the poles.",
        "Saturn's ring system is about 400,000 km (250,000 miles) wide but only 10 meters thick in some places.",
        "The rings of Saturn are not solid; they are made up of countless small particles.",
        "Saturn’s gravitational pull affects the orbits of nearby asteroids and comets.",
        "Saturn’s atmosphere has massive storms, including a long-lasting white storm seen periodically.",
        "Saturn’s hexagonal storm at the north pole is about 30,000 km (18,600 miles) wide.",
        "Saturn’s rings are mostly made of water ice, with some rocky debris.",
        "Saturn is named after the Roman god of agriculture.",
        "Titan, Saturn’s largest moon, has rivers, lakes, and seas of liquid hydrocarbons.",
        "Saturn emits more heat than it receives from the Sun due to internal processes.",
        "Saturn's rings are being gradually pulled into the planet by its gravity, meaning they may eventually disappear.",
        "Saturn’s interior is composed of a rocky core surrounded by metallic hydrogen.",
        "Saturn’s moon Enceladus has geysers that spew water into space.",
        "The Cassini spacecraft orbited Saturn for 13 years, providing invaluable data.",
        "The Encke Gap and Cassini Division are gaps within Saturn’s rings.",
        "Saturn has at least 7 major rings, labeled A to G.",
        "Saturn’s rings are younger than the planet itself, possibly only a few hundred million years old.",
        "Saturn’s rotation is so fast that it is visibly oblate (flattened at the poles).",
        "Some of Saturn’s moons, like Pandora and Prometheus, act as 'shepherd moons' by shaping the rings.",
        "Saturn’s rings may have formed from a moon that was torn apart by tidal forces.",
        "The Roche limit determines how close a moon can orbit a planet before breaking apart—Saturn's rings lie within this limit.",
        "Saturn’s rings cast shadows on the planet, which change with the seasons.",
        "Saturn experiences auroras at its poles, similar to Earth.",
        "The Huygens probe landed on Titan in 2005, sending back the first images from its surface.",
        "Saturn has seasonal changes due to its tilted axis, just like Earth.",
        "Saturn’s rings are continuously bombarded by meteoroids, altering their appearance.",
        "Saturn’s moon Mimas has a large crater that makes it resemble the Death Star from Star Wars.",
        "Saturn's atmosphere contains ammonia clouds, giving it a pale yellow hue.",
        "Saturn’s rings can be seen from Earth with a small telescope.",
        "Saturn has small moons embedded within its rings, called ring moons.",
        "Saturn’s core may be dissolving into its atmosphere over time.",
        "The Cassini spacecraft discovered water plumes erupting from Enceladus.",
        "Some of Saturn’s moons, like Iapetus, have one side much darker than the other.",
        "Saturn’s rings appear to disappear from view every 15 years when seen from Earth due to their thinness.",
        "Saturn's E-ring is made up of ice particles from Enceladus' geysers.",
        "Saturn’s rings have been observed to change shape and density over time.",
        "Saturn has a faint outer ring, called the Phoebe ring, which is much larger than the main rings.",
        "Saturn’s gravity is strong enough to slightly affect Jupiter’s orbit.",
        "Saturn's rings were likely first formed when a moon or comet shattered near the planet.",
        "Saturn’s storms can last for months or even years.",
        "Some of Saturn’s moons have orbits that swap places over time.",
        "Saturn’s magnetic field is aligned almost perfectly with its rotation axis, which is unusual among planets.",
        "Saturn’s interior heat may be generated by helium rain falling toward the core.",
        "Saturn’s northern hemisphere has a blue hue in some images due to scattering of sunlight.",
        "Saturn’s rings move at different speeds, depending on their distance from the planet.",
        "Saturn’s moons interact with the rings, creating waves and gaps.",
        "Saturn’s rings are made of billions of individual ice particles.",
        "Saturn’s radiation belts are weaker than Jupiter’s but still dangerous for spacecraft.",
        "Saturn has been a major target of space exploration due to its unique features.",
        "Saturn’s rings were originally thought to be solid but were later discovered to be made of countless tiny particles.",
        "Saturn's fast winds and clouds create alternating bands in its atmosphere.",
        "Saturn's ring system is one of the most striking features of the solar system.",
        "Saturn is sometimes called the 'Jewel of the Solar System' because of its beautiful rings.",
        "Some of Saturn’s smaller moons may have formed from ring material clumping together.",
        "Saturn's magnetosphere extends far into space and interacts with the solar wind.",
        "Saturn’s rings are constantly changing, and new structures continue to be discovered.",
        "Saturn’s gravity has influenced the orbits of some comets that pass through the solar system.",
        "The Cassini mission provided the most detailed images and data about Saturn and its moons.",
        "Saturn’s seasons last about seven Earth years each due to its long orbit around the Sun.",
        "Saturn’s rings are tilted at about 27 degrees relative to its orbit.",
        "Saturn is often used in science fiction as an iconic backdrop for space exploration stories.",
        "Saturn continues to be an important object of study for astronomers and planetary scientists.",
        "Saturn’s unique and complex ring system makes it one of the most fascinating planets in the solar system."
    };
    }


    private List<string> GetUranusFacts()
    {
        return new List<string>
    {
        "Uranus is the seventh planet from the Sun.",
        "Uranus is the third-largest planet in the solar system by diameter.",
        "Uranus is classified as an ice giant, along with Neptune.",
        "Uranus was the first planet discovered using a telescope.",
        "Sir William Herschel discovered Uranus in 1781.",
        "Uranus is named after the Greek god of the sky.",
        "Uranus has a pale blue-green color due to methane in its atmosphere.",
        "Uranus has 13 known rings, though they are faint and dark.",
        "Uranus orbits the Sun once every 84 Earth years.",
        "Uranus has 27 known moons, the largest of which is Titania.",
        "Uranus is tilted on its side at an angle of 98 degrees.",
        "Uranus’s extreme tilt makes it appear to roll along its orbit.",
        "Uranus's seasons last about 21 Earth years each.",
        "Uranus has a very cold atmosphere, with temperatures as low as -224°C (-371°F).",
        "Uranus's winds can reach speeds of up to 900 km/h (560 mph).",
        "Uranus's rings are much thinner and darker than Saturn’s.",
        "Uranus’s magnetic field is tilted compared to its rotational axis.",
        "Uranus was originally thought to be a star before being identified as a planet.",
        "The Voyager 2 spacecraft is the only probe to have visited Uranus.",
        "Voyager 2 flew past Uranus in 1986, providing most of what we know about the planet.",
        "Uranus’s rings were discovered in 1977 when they blocked starlight.",
        "Uranus rotates in the opposite direction to most planets, a motion called retrograde rotation.",
        "Uranus's moon Miranda has some of the most unusual geological features in the solar system.",
        "Uranus’s atmosphere is made mostly of hydrogen, helium, and methane.",
        "Methane in Uranus’s atmosphere absorbs red light, giving it a blue-green appearance.",
        "Uranus’s moons are named after characters from Shakespeare and Alexander Pope’s works.",
        "The largest moons of Uranus are Titania, Oberon, Umbriel, Ariel, and Miranda.",
        "Uranus’s gravity is slightly weaker than Earth's.",
        "Uranus’s magnetic field is offset from its center by a third of the planet’s radius.",
        "Uranus has a faint, dusty outer ring called the Zeta ring.",
        "Uranus’s core is much smaller compared to the gas giants Jupiter and Saturn.",
        "Uranus emits very little heat compared to other gas giants.",
        "Uranus's axis of rotation may have been tilted by a giant collision in the past.",
        "Uranus's clouds are composed of water, ammonia, and methane ice.",
        "Uranus is about four times wider than Earth.",
        "Uranus’s atmosphere extends for thousands of kilometers into space.",
        "Uranus has been observed by telescopes since ancient times, but it wasn’t recognized as a planet.",
        "Uranus’s equator is nearly perpendicular to its orbit due to its extreme tilt.",
        "One day on Uranus lasts about 17 hours and 14 minutes.",
        "Uranus’s moons show signs of past geological activity, including ice volcanoes.",
        "Uranus has an unusual magnetic field that wobbles as the planet rotates.",
        "Uranus’s rings are composed mostly of large, dark particles.",
        "Uranus is sometimes called an 'ice giant' because of the high amount of ice in its interior.",
        "The winds on Uranus blow in the direction of its rotation.",
        "The methane in Uranus’s upper atmosphere creates thin, wispy clouds.",
        "Uranus’s moons have diverse landscapes, including cliffs, valleys, and frozen plains.",
        "Uranus’s blue color makes it one of the most distinct planets in the solar system.",
        "Uranus’s upper atmosphere contains hydrogen sulfide, which smells like rotten eggs.",
        "Uranus is more than 2.8 billion kilometers (1.8 billion miles) from the Sun.",
        "The sun appears much dimmer from Uranus than from Earth.",
        "Uranus's atmosphere gets colder the higher you go, unlike Earth's.",
        "Uranus’s seasons are the longest of any planet in the solar system.",
        "One hemisphere of Uranus is in total darkness for 42 years at a time.",
        "Uranus’s rings are made of extremely dark material, possibly carbon-rich compounds.",
        "Uranus is the least dense of all the giant planets.",
        "Uranus’s core is estimated to be only slightly warmer than Earth’s core.",
        "Scientists believe Uranus has a deep, icy mantle beneath its atmosphere.",
        "Uranus was almost named 'George’s Star' after King George III.",
        "The tilt of Uranus causes some of its moons to orbit in unusual patterns.",
        "Uranus is so far from the Sun that sunlight takes about 2 hours and 40 minutes to reach it.",
        "Uranus is slightly larger in diameter than Neptune but has less mass.",
        "Uranus’s surface is not solid; it transitions gradually from gas to liquid.",
        "Uranus has a very thin exosphere, the outermost layer of its atmosphere.",
        "Uranus appears featureless compared to other planets, though storms have been detected.",
        "The Great Dark Spot, a storm seen on Neptune, has no known counterpart on Uranus.",
        "The rings of Uranus may have formed from a shattered moon.",
        "Uranus is the coldest planet in the solar system, even colder than Neptune.",
        "Uranus’s magnetic field is irregular and stronger in some areas than others.",
        "Scientists believe Uranus’s strange rotation could be due to a massive collision early in its history.",
        "Because of its tilt, Uranus experiences extreme variations in sunlight and darkness.",
        "Uranus's magnetic field is lopsided, making its auroras appear in strange locations.",
        "The discovery of Uranus expanded the known boundaries of the solar system.",
        "Despite its distance, Uranus can be seen with the naked eye under ideal conditions.",
        "Uranus’s ring system is younger than the planet itself.",
        "Uranus’s moons may contain underground oceans beneath their icy crusts.",
        "Triton, Neptune’s largest moon, may have originally been a moon of Uranus before being captured by Neptune.",
        "Uranus was once thought to be a comet before being recognized as a planet.",
        "Uranus's extreme tilt affects how its atmosphere circulates.",
        "Uranus is one of the least explored planets in the solar system.",
        "Some theories suggest Uranus may have formed closer to the Sun before migrating outward.",
        "The color of Uranus is lighter than Neptune because it has less methane in its atmosphere.",
        "Uranus's ring system is more similar to Jupiter’s than Saturn’s.",
        "Uranus's magnetic field rotates in a chaotic manner due to its tilt.",
        "Uranus has auroras similar to Earth's, but they occur in unexpected places.",
        "Uranus’s rings were discovered accidentally when astronomers were observing a distant star.",
        "Uranus’s gravity is about 89% of Earth’s, meaning you would weigh less there.",
        "Uranus has never been visited by a dedicated space probe—only a flyby by Voyager 2.",
        "Some astronomers believe that Uranus might have a subsurface layer of superionic water.",
        "Uranus continues to be a mysterious planet with many unanswered questions.",
        "Future missions are being planned to explore Uranus in more detail.",
        "Uranus remains one of the most unique and intriguing planets in the solar system."
    };
    }


    private List<string> GetNeptuneFacts()
    {
        return new List<string>
    {
        "Neptune is the eighth and farthest planet from the Sun.",
        "Neptune is the fourth-largest planet in diameter in the solar system.",
        "Neptune is classified as an ice giant, like Uranus.",
        "Neptune was discovered on September 23, 1846.",
        "Neptune was the first planet located through mathematical predictions.",
        "Johann Galle and Heinrich d'Arrest confirmed Neptune’s existence based on predictions by Urbain Le Verrier.",
        "Neptune is named after the Roman god of the sea.",
        "Neptune has 14 known moons, the largest of which is Triton.",
        "Neptune is the only planet in the solar system that cannot be seen with the naked eye.",
        "Neptune appears blue due to methane in its atmosphere absorbing red light.",
        "Neptune's atmosphere is composed mostly of hydrogen, helium, and methane.",
        "Neptune's winds are the fastest in the solar system, reaching up to 2,100 km/h (1,300 mph).",
        "A year on Neptune lasts about 165 Earth years.",
        "Neptune has six known rings, which are faint and composed of ice and dust.",
        "The rings of Neptune are named after astronomers who contributed to its discovery.",
        "Neptune rotates once every 16 hours.",
        "Neptune is 30 times farther from the Sun than Earth.",
        "Neptune's largest moon, Triton, orbits in the opposite direction of the planet’s rotation.",
        "Triton is believed to be a captured Kuiper Belt object.",
        "Triton has geysers that spew nitrogen gas into space.",
        "Neptune has an extremely strong magnetic field, 27 times stronger than Earth's.",
        "Neptune experiences extreme seasonal changes due to its long orbit.",
        "The Great Dark Spot was a massive storm on Neptune, similar to Jupiter’s Great Red Spot.",
        "Neptune's Great Dark Spot disappeared in later observations, showing that its storms change over time.",
        "Neptune emits more heat than it receives from the Sun.",
        "The first spacecraft to visit Neptune was Voyager 2 in 1989.",
        "Voyager 2 is the only spacecraft to have flown past Neptune.",
        "Neptune's temperature can drop to -214°C (-353°F).",
        "Neptune has a rocky core surrounded by a thick layer of water, ammonia, and methane ice.",
        "Neptune's clouds are made of frozen methane crystals.",
        "Neptune’s atmosphere has bright white clouds that resemble cirrus clouds on Earth.",
        "Neptune’s gravity is 17% stronger than Earth’s.",
        "Neptune is sometimes farther from the Sun than Pluto due to Pluto’s elliptical orbit.",
        "Neptune has a tilted axis of 28 degrees, similar to Earth’s 23.5-degree tilt.",
        "Neptune has a faint but active aurora due to its strong magnetic field.",
        "Neptune's rings are made of dark material, likely organic compounds.",
        "Neptune has an internal heat source that drives its violent storms.",
        "Neptune’s storms can last for years or even decades.",
        "Neptune's rings contain clumps and arcs, which are unusual compared to other planetary rings.",
        "Neptune takes about 16 hours to complete one rotation.",
        "Neptune’s storms create massive waves in its atmosphere.",
        "Neptune has a dynamic climate, with clouds forming and disappearing rapidly.",
        "Neptune's Great Dark Spot was similar in size to Earth.",
        "Neptune is about four times the diameter of Earth.",
        "Neptune's upper atmosphere experiences extreme pressure changes.",
        "Neptune's winds blow in the opposite direction of its rotation at certain latitudes.",
        "Neptune's interior is mostly water, ammonia, and methane ice.",
        "Neptune's blue color is deeper than Uranus’s due to different atmospheric compositions.",
        "Neptune's atmosphere gradually transitions into a superheated ocean-like layer.",
        "Neptune has a tilted and offset magnetic field, similar to Uranus.",
        "The discovery of Neptune confirmed that Uranus was being gravitationally influenced by another planet.",
        "Neptune is 17 times more massive than Earth.",
        "Neptune's clouds move at different speeds, creating complex weather patterns.",
        "Neptune’s core is thought to be similar to Earth’s, but much larger.",
        "Neptune's faint rings were confirmed by Voyager 2.",
        "Neptune’s outermost ring, Adams, contains bright arcs named Liberty, Equality, and Fraternity.",
        "Triton has a thin atmosphere mostly made of nitrogen.",
        "Triton is slowly moving closer to Neptune and will eventually be torn apart by gravity.",
        "Triton is the coldest known body in the solar system, with a surface temperature of -235°C (-391°F).",
        "Neptune’s moon Nereid has one of the most eccentric orbits of any moon in the solar system.",
        "Neptune’s rings may be relatively young compared to the planet.",
        "Neptune’s magnetic field is not aligned with its rotation axis.",
        "Neptune has the fastest winds recorded in the solar system.",
        "Neptune has a 'Scooter' storm system that moves faster than other clouds.",
        "Neptune's dark spots may be holes in its atmosphere rather than storms.",
        "Neptune's auroras are much weaker than Jupiter’s and Saturn’s.",
        "Neptune’s atmosphere is extremely dynamic, with high-speed jet streams.",
        "Neptune is the densest of the giant planets in our solar system.",
        "Triton’s polar caps contain frozen nitrogen and methane.",
        "Neptune’s core is much hotter than its atmosphere.",
        "Neptune’s storms are powered by heat escaping from the planet’s interior.",
        "Neptune’s rings were first detected in 1984 but confirmed by Voyager 2.",
        "Neptune’s rings are composed mostly of microscopic ice and dust particles.",
        "Neptune's interior pressure is millions of times greater than Earth’s atmosphere.",
        "Scientists suspect that Neptune’s interior contains a layer of superionic water.",
        "Neptune’s equatorial region is warmer than expected, possibly due to deep currents.",
        "Neptune's clouds contain elements like hydrogen sulfide, which smells like rotten eggs.",
        "Neptune’s polar regions are warmer than expected, but the reason is still unknown.",
        "Neptune’s fast rotation helps generate its powerful magnetic field.",
        "Neptune's extreme winds may be driven by complex internal processes.",
        "Neptune is still geologically active despite its great distance from the Sun.",
        "Neptune’s moon Proteus is irregularly shaped and heavily cratered.",
        "Neptune's rings may have formed from a moon that was broken apart.",
        "Neptune’s auroras occur at unusual locations due to its tilted magnetic field.",
        "Neptune is often referred to as the 'Blue Giant.'",
        "Neptune’s storms have been observed changing over just a few months.",
        "Neptune was once considered the last planet in the solar system before Pluto was reclassified.",
        "Neptune has been visited only once by a spacecraft.",
        "Neptune's mass helps keep the Kuiper Belt in place.",
        "Neptune’s exploration remains a priority for future space missions.",
        "Despite its great distance, Neptune continues to fascinate scientists and astronomers."
    };
    }


    private List<string> GetSunFacts()
    {
        return new List<string>
    {
        "The Sun is the center of the solar system.",
        "The Sun is a massive ball of hot plasma primarily composed of hydrogen and helium.",
        "The Sun accounts for about 99.8% of the total mass of the solar system.",
        "The Sun’s diameter is about 1.39 million kilometers (864,000 miles).",
        "The Sun's core temperature reaches around 15 million degrees Celsius (27 million degrees Fahrenheit).",
        "The Sun generates energy through nuclear fusion, converting hydrogen into helium.",
        "The Sun's energy production is equivalent to 386 billion megawatts per second.",
        "The Sun is classified as a G-type main-sequence star (G2V).",
        "The Sun is about 4.6 billion years old.",
        "The Sun has completed about 20 orbits around the Milky Way since its formation.",
        "The Sun takes approximately 225-250 million years to orbit the Milky Way once.",
        "The Sun's light takes about 8 minutes and 20 seconds to reach Earth.",
        "The Sun's surface temperature is about 5,500°C (9,932°F).",
        "The Sun's atmosphere consists of the photosphere, chromosphere, and corona.",
        "The corona, the Sun's outermost layer, is hotter than its surface, reaching millions of degrees.",
        "The Sun's magnetic field is responsible for solar storms and sunspots.",
        "Sunspots are cooler regions on the Sun's surface caused by magnetic activity.",
        "The Sun follows an 11-year solar cycle, with periods of high and low sunspot activity.",
        "Solar flares are sudden bursts of energy from the Sun’s surface.",
        "Coronal Mass Ejections (CMEs) are large eruptions of plasma and magnetic field from the Sun.",
        "Solar storms can disrupt satellites, power grids, and communication systems on Earth.",
        "The Sun’s gravity keeps all planets in orbit around it.",
        "The Sun loses about 4 million tons of mass per second due to energy radiation.",
        "The Sun is roughly 109 times the diameter of Earth.",
        "More than 1.3 million Earths could fit inside the Sun.",
        "The Sun's core is where nuclear fusion occurs, producing vast amounts of energy.",
        "The energy produced in the core takes thousands to millions of years to reach the surface.",
        "The Sun emits radiation across the electromagnetic spectrum, including visible light, UV, and X-rays.",
        "The Sun's ultraviolet (UV) rays are responsible for sunburns on Earth.",
        "Without the Sun’s heat and light, life on Earth would not be possible.",
        "The Sun's gravity is 28 times stronger than Earth's gravity.",
        "The Sun’s mass is about 333,000 times that of Earth.",
        "The Sun rotates on its axis, but different parts rotate at different speeds (differential rotation).",
        "The Sun rotates approximately once every 25 days at the equator and 35 days at the poles.",
        "The Sun's energy influences Earth's climate and weather patterns.",
        "A solar eclipse occurs when the Moon blocks sunlight from reaching Earth.",
        "A total solar eclipse reveals the Sun’s corona, which is normally hidden by its brightness.",
        "A solar wind, composed of charged particles, constantly flows from the Sun.",
        "The solar wind creates the heliosphere, a protective bubble around the solar system.",
        "Auroras (Northern and Southern Lights) are caused by the interaction of solar wind with Earth's atmosphere.",
        "The Sun will eventually exhaust its hydrogen fuel and become a red giant.",
        "In about 5 billion years, the Sun will expand and engulf Mercury, Venus, and possibly Earth.",
        "After its red giant phase, the Sun will shed its outer layers and become a white dwarf.",
        "The Sun's white dwarf remnant will slowly cool over billions of years.",
        "The Sun's brightness and temperature have gradually increased over its lifetime.",
        "The Sun is moving at about 828,000 km/h (514,000 mph) through the Milky Way.",
        "The Sun is part of the Orion Arm of the Milky Way galaxy.",
        "The Sun’s magnetic field flips approximately every 11 years.",
        "Sunspots were first observed by Galileo Galilei in the early 1600s.",
        "The Sun emits neutrinos, tiny particles that pass through almost everything, including Earth.",
        "The Sun's magnetic activity can cause radio signal disruptions on Earth.",
        "Solar prominences are giant loops of plasma extending from the Sun’s surface.",
        "The Sun’s outer layers are constantly expanding due to its strong radiation.",
        "The Sun’s total lifespan is estimated to be about 10 billion years.",
        "The Sun contains about 74% hydrogen, 24% helium, and traces of other elements.",
        "The Sun's heat and radiation shape the atmospheres of planets in the solar system.",
        "The Sun's magnetic influence extends beyond Pluto, reaching the heliopause.",
        "The Parker Solar Probe, launched in 2018, is the closest spacecraft to the Sun.",
        "The Sun’s energy output is nearly constant but experiences slight variations over time.",
        "Solar maximum is the period of highest sunspot activity in the 11-year solar cycle.",
        "Solar minimum is the period of lowest sunspot activity.",
        "The Sun's rays help plants grow through photosynthesis.",
        "Solar radiation can be converted into electricity using solar panels.",
        "The Sun’s energy production has been stable enough to support life for billions of years.",
        "The Sun influences space weather, which can affect satellites and astronauts.",
        "The Sun’s outer edge is not solid but transitions gradually into space.",
        "The Sun's surface has a boiling-like texture due to convective currents.",
        "The Sun’s density is about 1.41 times that of water.",
        "The Sun has a powerful influence on Earth’s seasons and climate.",
        "The Sun is one of billions of stars in the Milky Way galaxy.",
        "Scientists use helioseismology to study the Sun’s interior by analyzing its vibrations.",
        "The Sun emits solar particles that can be harmful to astronauts without proper shielding.",
        "The Sun’s magnetic field extends far beyond Pluto and is known as the heliosphere.",
        "The Sun will shine as a white dwarf for billions of years after it exhausts its fuel.",
        "The Sun’s radiation pressure helps push away cosmic dust from the solar system.",
        "The Sun’s light creates shadows on Earth, which change depending on the time of day.",
        "The Sun’s rays travel at the speed of light, about 300,000 km/s (186,000 miles per second).",
        "The Sun’s core pressure is 250 billion times Earth’s atmospheric pressure.",
        "The Sun influences the positions of comets in the solar system.",
        "The Sun has a faint companion star hypothesis, but no evidence supports this.",
        "The Sun’s total energy output could power human civilization for millions of years.",
        "The Sun’s core is so dense that it takes a photon thousands of years to escape.",
        "The Sun will never go supernova because it is not massive enough.",
        "The Sun’s future white dwarf stage will be surrounded by a planetary nebula.",
        "The Sun’s light is essential for vitamin D production in humans.",
        "Solar activity influences Earth's ionosphere, affecting radio communications.",
        "Solar storms can create beautiful but dangerous geomagnetic storms.",
        "The Sun is sometimes called Sol, from the Latin word for Sun.",
        "The Sun’s radiation pressure helps form the tails of comets.",
        "The Sun’s gravitational pull extends far beyond Pluto.",
        "The Sun’s outer edges constantly expand and contract due to dynamic processes.",
        "Understanding the Sun helps scientists predict space weather events."
    };
    }

}
